export const listMenuItems = [
  {
    key: '1',
    icon: '',
    alt: 'Delay icon',
    text: 'delay',
    type: 'delay',
  },
  {
    key: '2',
    icon: '',
    alt: 'Keyboard icon',
    text: 'keyboard function',
    type: 'keyboard',
  },
  {
    key: '3',
    icon: '',
    alt: 'Mouse icon',
    text: 'mouse function',
    type: 'mouse',
  },
  {
    key: '4',
    icon: '',
    alt: 'Macro icon',
    text: 'macro',
    type: 'macro',
  },
  {
    key: '5',
    icon: '',
    alt: 'Switch device icon',
    text: 'switch device profile',
    type: 'switchDevice',
  },
  {
    key: '6',
    icon: '',
    alt: 'Switch lighting icon',
    text: 'switch lighting',
    type: 'switchLighting',
  },
  {
    key: '7',
    icon: '',
    alt: 'Launch icon',
    text: 'Launch',
    type: 'launch',
  },
  {
    key: '8',
    icon: '',
    alt: 'Command icon',
    text: 'run command',
    type: 'command',
  },
  {
    key: '9',
    icon: '',
    alt: 'Multimedia icon',
    text: 'multimedia',
    type: 'multimedia',
  },
  {
    key: '10',
    icon: '',
    alt: 'Text icon',
    text: 'text function',
    type: 'text',
  },
  {
    key: '11',
    icon: '',
    alt: 'Loop icon',
    text: 'loop',
    type: 'loop',
  },
];
